#!/usr/bin/env bash
# Remove everything-codex-unity files from a Unity project, with backups.

set -euo pipefail

PROJECT_DIR="."
INSTALL_PROJECT=1
REMOVE_MARKETPLACE=0
CODEX_HOME="${CODEX_HOME:-$HOME/.codex}"
KEEP_BACKUP=1

while [[ $# -gt 0 ]]; do
    case "$1" in
        --project-dir)
            PROJECT_DIR="$2"; shift 2 ;;
        --codex-marketplace)
            REMOVE_MARKETPLACE=1; shift ;;
        --codex-marketplace-only)
            REMOVE_MARKETPLACE=1; INSTALL_PROJECT=0; shift ;;
        --codex-home)
            CODEX_HOME="$2"; shift 2 ;;
        --no-backup)
            KEEP_BACKUP=0; shift ;;
        --help|-h)
            echo "Usage: uninstall.sh [--project-dir <path>] [--codex-marketplace] [--codex-marketplace-only] [--codex-home <path>] [--no-backup]"
            exit 0 ;;
        *)
            echo "Unknown option: $1" >&2
            exit 1 ;;
    esac
done

if [ "$INSTALL_PROJECT" -eq 1 ]; then
    PROJECT_DIR=$(cd "$PROJECT_DIR" && pwd)
fi
CODEX_HOME=$(mkdir -p "$CODEX_HOME" && cd "$CODEX_HOME" && pwd)
STAMP=$(date +%Y%m%d%H%M%S)
BACKUP_DIR="$PROJECT_DIR/.codex-unity-uninstall-backup-$STAMP"

remove_path() {
    local path="$1"
    if [ ! -e "$path" ]; then
        return 0
    fi
    if [ "$KEEP_BACKUP" -eq 1 ]; then
        mkdir -p "$BACKUP_DIR"
        mv "$path" "$BACKUP_DIR/$(basename "$path")"
        echo "Backed up $(basename "$path")"
    else
        rm -rf "$path"
        echo "Removed $(basename "$path")"
    fi
}

remove_codex_config_section() {
    local config_file="$1"
    local tmp_file
    if [ ! -f "$config_file" ]; then
        return 0
    fi
    tmp_file=$(mktemp)
    awk '
        /^\[marketplaces\.everything-codex-unity\]$/ { skip=1; next }
        /^\[plugins\."everything-codex-unity@everything-codex-unity"\]$/ { skip=1; next }
        /^\[/ { skip=0 }
        skip != 1 { print }
    ' "$config_file" > "$tmp_file"
    mv "$tmp_file" "$config_file"
    echo "Removed Codex config entries"
}

remove_marketplace() {
    local marketplace_root="$CODEX_HOME/marketplaces/everything-codex-unity"
    local backup="$CODEX_HOME/marketplaces/everything-codex-unity.uninstall-backup-$STAMP"

    if [ -d "$marketplace_root" ]; then
        if [ "$KEEP_BACKUP" -eq 1 ]; then
            if [ -e "$backup" ]; then
                backup="${backup}.$$"
            fi
            mv "$marketplace_root" "$backup"
            echo "Backed up Codex marketplace to: $backup"
        else
            rm -rf "$marketplace_root"
            echo "Removed Codex marketplace"
        fi
    fi
    remove_codex_config_section "$CODEX_HOME/config.toml"
}

if [ "$INSTALL_PROJECT" -eq 1 ]; then
    remove_path "$PROJECT_DIR/.codex-plugin"
    remove_path "$PROJECT_DIR/skills"
    remove_path "$PROJECT_DIR/.codex-legacy"
    remove_path "$PROJECT_DIR/.codex-unity"
    remove_path "$PROJECT_DIR/.mcp.json"

    if [ -f "$PROJECT_DIR/AGENTS.md" ] && grep -q "everything-codex-unity" "$PROJECT_DIR/AGENTS.md" 2>/dev/null; then
        remove_path "$PROJECT_DIR/AGENTS.md"
    elif [ -f "$PROJECT_DIR/AGENTS.md" ]; then
        echo "Kept AGENTS.md because it does not look generated by everything-codex-unity."
    fi
fi

if [ "$KEEP_BACKUP" -eq 1 ] && [ -d "$BACKUP_DIR" ]; then
    echo "Backup written to: $BACKUP_DIR"
fi

if [ "$REMOVE_MARKETPLACE" -eq 1 ]; then
    remove_marketplace
fi

echo "everything-codex-unity uninstalled."
