#!/usr/bin/env bash
# Remove everything-codex-unity files from a Unity project, with backups.

set -euo pipefail

PROJECT_DIR="."
PROJECT_DIR_SET=0
INSTALL_PROJECT=1
REMOVE_MARKETPLACE=0
CODEX_HOME="${CODEX_HOME:-$HOME/.codex}"
KEEP_BACKUP=1

while [[ $# -gt 0 ]]; do
    case "$1" in
        --project-dir)
            PROJECT_DIR="$2"; PROJECT_DIR_SET=1; shift 2 ;;
        --codex-marketplace)
            REMOVE_MARKETPLACE=1; INSTALL_PROJECT=0; shift ;;
        --codex-home)
            CODEX_HOME="$2"; shift 2 ;;
        --no-backup)
            KEEP_BACKUP=0; shift ;;
        --help|-h)
            echo "Usage: uninstall.sh [--project-dir <path> | --codex-marketplace] [--codex-home <path>] [--no-backup]"
            echo ""
            echo "Note: --project-dir and --codex-marketplace are mutually exclusive."
            exit 0 ;;
        *)
            echo "Unknown option: $1" >&2
            exit 1 ;;
    esac
done

if [ "$REMOVE_MARKETPLACE" -eq 1 ] && [ "$PROJECT_DIR_SET" -eq 1 ]; then
    echo "--project-dir and --codex-marketplace are mutually exclusive." >&2
    exit 1
fi

if [ "$INSTALL_PROJECT" -eq 1 ]; then
    PROJECT_DIR=$(cd "$PROJECT_DIR" && pwd)
fi
if [ "$REMOVE_MARKETPLACE" -eq 1 ]; then
    CODEX_HOME=$(mkdir -p "$CODEX_HOME" && cd "$CODEX_HOME" && pwd)
fi
SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
source "$SCRIPT_DIR/scripts/codex-marketplace.sh"
STAMP=$(date +%Y%m%d%H%M%S)
BACKUP_DIR="$PROJECT_DIR/.codex-unity-uninstall-backup-$STAMP"

remove_path() {
    local path="$1"
    if [ ! -e "$path" ]; then
        return 0
    fi
    if [ "$KEEP_BACKUP" -eq 1 ]; then
        mkdir -p "$BACKUP_DIR"
        mv "$path" "$BACKUP_DIR/$(basename "$path")"
        echo "Backed up $(basename "$path")"
    else
        rm -rf "$path"
        echo "Removed $(basename "$path")"
    fi
}

remove_marketplace() {
    ecu_uninstall_marketplace "$CODEX_HOME" "$KEEP_BACKUP"
}

has_project_install() {
    [ -f "$PROJECT_DIR/.codex-plugin/plugin.json" ] && grep -q '"name"[[:space:]]*:[[:space:]]*"everything-codex-unity"' "$PROJECT_DIR/.codex-plugin/plugin.json" 2>/dev/null && return 0
    [ -f "$PROJECT_DIR/skills/workflows/unity-workflow/SKILL.md" ] && grep -q '^name:[[:space:]]*unity-workflow' "$PROJECT_DIR/skills/workflows/unity-workflow/SKILL.md" 2>/dev/null && return 0
    [ -f "$PROJECT_DIR/skills/unity-project-rules/SKILL.md" ] && grep -q '^name:[[:space:]]*unity-project-rules' "$PROJECT_DIR/skills/unity-project-rules/SKILL.md" 2>/dev/null && return 0
    [ -f "$PROJECT_DIR/.codex-legacy/commands/unity-workflow.md" ] && return 0
    [ -f "$PROJECT_DIR/.codex-unity/scripts/generate-agents-md.sh" ] && return 0
    [ -f "$PROJECT_DIR/AGENTS.md" ] && grep -q "everything-codex-unity" "$PROJECT_DIR/AGENTS.md" 2>/dev/null && return 0
    return 1
}

has_marketplace_install() {
    local marketplace_json="$HOME/.agents/plugins/marketplace.json"
    local config_file="$CODEX_HOME/config.toml"

    [ -d "$HOME/plugins/$ECU_PLUGIN_NAME" ] && return 0
    [ -f "$config_file" ] && grep -q "everything-codex-unity@everything-codex-unity" "$config_file" 2>/dev/null && return 0
    if [ -f "$marketplace_json" ] && command -v python3 >/dev/null 2>&1; then
        python3 - "$marketplace_json" <<'PY' && return 0
import json
import sys
from pathlib import Path

try:
    data = json.loads(Path(sys.argv[1]).read_text())
except Exception:
    sys.exit(1)
for plugin in data.get("plugins", []):
    if plugin.get("name") == "everything-codex-unity":
        sys.exit(0)
sys.exit(1)
PY
    fi
    return 1
}

if [ "$INSTALL_PROJECT" -eq 1 ]; then
    if ! has_project_install; then
        echo "No everything-codex-unity project install found in $PROJECT_DIR." >&2
        exit 1
    fi

    remove_path "$PROJECT_DIR/.codex-plugin"
    remove_path "$PROJECT_DIR/skills"
    remove_path "$PROJECT_DIR/.codex-legacy"
    remove_path "$PROJECT_DIR/.codex-unity"
    remove_path "$PROJECT_DIR/.mcp.json"

    if [ -f "$PROJECT_DIR/AGENTS.md" ] && grep -q "everything-codex-unity" "$PROJECT_DIR/AGENTS.md" 2>/dev/null; then
        remove_path "$PROJECT_DIR/AGENTS.md"
    elif [ -f "$PROJECT_DIR/AGENTS.md" ]; then
        echo "Kept AGENTS.md because it does not look generated by everything-codex-unity."
    fi
fi

if [ "$KEEP_BACKUP" -eq 1 ] && [ -d "$BACKUP_DIR" ]; then
    echo "Backup written to: $BACKUP_DIR"
fi

if [ "$REMOVE_MARKETPLACE" -eq 1 ]; then
    if ! has_marketplace_install; then
        echo "No Codex marketplace install found for $ECU_PLUGIN_NAME." >&2
        exit 1
    fi

    remove_marketplace
fi

echo "everything-codex-unity uninstalled."
